export const SET_STORE_FURNITURES = 'SET_STORE_FURNITURES'
export const SET_STORE_FURNITURES_SUCCESS = 'SET_STORE_FURNITURES_SUCCESS'
export const SET_STORE_FURNITURES_FAIL = 'SET_STORE_FURNITURES_FAIL'
export const IS_FURNITURE_ADDED_TO_CART = 'IS_FURNITURE_ADDED_TO_CART'


export const SET_CART_FURNITURES = 'SET_CART_FURNITURES'
export const SET_CART_FURNITURES_SUCCESS = 'SET_CART_FURNITURES_SUCCESS'
export const SET_CART_FURNITURES_FAIL = 'SET_CART_FURNITURES_FAIL'
export const BUY_ITEM_FROM_CART = 'BUY_ITEM_FROM_CART'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'
export const UPDATE_PURCHASE = 'UPDATE_PURCHASE'
export const SET_ORDERS = 'SET_ORDERS'
export const SET_ORDERS_SUCCESS = 'SET_ORDERS_SUCCESS'
export const SET_ORDERS_FAIL = 'SET_ORDERS_FAIL'

export const ADD_CONTACT = 'ADD_CONTACT'
export const  ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS'
export const  SHOW_FORM = 'SHOW_FORM'

export const SET_INVENTORY = 'SET_INVENTORY'
export const SET_INVENTORY_SUCCESS = 'SET_INVENTORY_SUCCESS'
export const SET_INVENTORY_FAIL = 'SET_INVENTORY_FAIL'

export const REDIRECT_PATH = 'REDIRECT_PATH'



export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

